# -*- coding: utf-8 -*-
"""py1IESB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FA68q0EglksiHEC-NF1kQbaFq8nUh4fT
"""

3 + 3

name = 'Caio'
age = '23'
alive = True
lazy = False

print(name + ' tem ' + age + ' e está vivo?', alive)

a = 1
b = a

a = 2
print(a)
print(b)

aNone = None
print(aNone)

idade = int(input('Qual é sua idade? '))
if idade >= 18:
    print('Você pode dirigir')
else:
    print('voce é menor de idade')
